"""
SAR Report Generator — Auto-generates Suspicious Activity Reports.
Generates compliance-ready SAR narratives with regulatory citations,
fund trace subgraphs, and PDF export capability.
"""

import json
import os
from datetime import datetime
from typing import Dict, List, Optional
import pandas as pd
import networkx as nx


# Filing institution defaults — overridden by env vars BANK_NAME / COMPLIANCE_OFFICER.
# Production deployment sets these once via docker-compose env; demo mode shows the
# explicit "[Set BANK_NAME env var]" hint so an evaluator sees the placeholder is
# intentional, not forgotten.
DEFAULT_BANK_NAME = os.environ.get("BANK_NAME") or "[Set BANK_NAME env var]"
DEFAULT_COMPLIANCE_OFFICER = os.environ.get("COMPLIANCE_OFFICER") or "[Set COMPLIANCE_OFFICER env var]"


SAR_TEMPLATE = """
SUSPICIOUS ACTIVITY REPORT (SAR)
=================================
Report ID: {report_id}
Generated: {generated_date}
Filing Institution: {bank_name}
Priority: {priority}

═══════════════════════════════════════════════════════════════

SECTION 1: REPORTING INSTITUTION INFORMATION
─────────────────────────────────────────────
Institution Name: {bank_name}
Branch: {branch}
Reporting Officer: {compliance_officer}
Date of Detection: {detection_date}

═══════════════════════════════════════════════════════════════

SECTION 2: SUSPECT INFORMATION
──────────────────────────────
{suspect_information}

═══════════════════════════════════════════════════════════════

SECTION 3: SUSPICIOUS ACTIVITY DESCRIPTION
───────────────────────────────────────────
{activity_description}

═══════════════════════════════════════════════════════════════

SECTION 4: TRANSACTION DETAILS
──────────────────────────────
{transaction_details}

═══════════════════════════════════════════════════════════════

SECTION 5: FUND FLOW ANALYSIS
─────────────────────────────
{fund_flow_analysis}

═══════════════════════════════════════════════════════════════

SECTION 6: PATTERN ANALYSIS & REASONING
───────────────────────────────────────
{pattern_analysis}

═══════════════════════════════════════════════════════════════

SECTION 7: REGULATORY CITATIONS
──────────────────────────────
{regulatory_citations}

═══════════════════════════════════════════════════════════════

SECTION 8: RECOMMENDATIONS
──────────────────────────
{recommendations}

═══════════════════════════════════════════════════════════════

SECTION 9: SUPPORTING DOCUMENTS
──────────────────────────────
{supporting_documents}

═══════════════════════════════════════════════════════════════

Declaration: This report is filed pursuant to RBI Master Direction on KYC
(Chapter VII — Suspicious Transaction Reporting) and PMLA 2002 requirements.
The information contained herein is confidential and subject to Section 66
of PMLA regarding tipping-off provisions.

Generated by RUDRA — AI-Powered Fund Flow Intelligence System
"""


class SARGenerator:
    """Generate Suspicious Activity Reports from fraud alerts."""

    def __init__(self, graph: nx.DiGraph, transactions: pd.DataFrame,
                 alerts: List[Dict], fraud_cases: List[Dict]):
        self.graph = graph
        self.transactions = transactions
        self.alerts = alerts
        self.fraud_cases = fraud_cases
        self.report_counter = 0

    def generate_sar(self, alert: Dict) -> Dict:
        """Generate a full SAR report for a given alert."""
        self.report_counter += 1
        report_id = f"SAR-2026-{self.report_counter:04d}"
        entities = alert.get("entities", [])

        suspect_info = self._build_suspect_info(entities)
        activity_desc = self._build_activity_description(alert)
        txn_details = self._build_transaction_details(entities, alert)
        fund_flow = self._build_fund_flow_analysis(entities, alert)
        pattern = self._build_pattern_analysis(alert)
        citations = self._build_regulatory_citations(alert)
        recommendations = self._build_recommendations(alert)
        supporting = self._build_supporting_docs(report_id, alert)

        branch = "Multiple" if len(set(self.graph.nodes[e].get("branch", "") for e in entities if self.graph.has_node(e))) > 1 else "N/A"

        # Reading the env var here (not at module load) so docker-compose `environment:`
        # overrides + tests that monkey-patch os.environ both work cleanly.
        bank_name = os.environ.get("BANK_NAME") or DEFAULT_BANK_NAME
        compliance_officer = os.environ.get("COMPLIANCE_OFFICER") or DEFAULT_COMPLIANCE_OFFICER

        report_text = SAR_TEMPLATE.format(
            report_id=report_id,
            generated_date=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            priority=alert.get("severity", "HIGH"),
            branch=branch,
            detection_date=datetime.now().strftime("%Y-%m-%d"),
            bank_name=bank_name,
            compliance_officer=compliance_officer,
            suspect_information=suspect_info,
            activity_description=activity_desc,
            transaction_details=txn_details,
            fund_flow_analysis=fund_flow,
            pattern_analysis=pattern,
            regulatory_citations=citations,
            recommendations=recommendations,
            supporting_documents=supporting,
        )

        return {
            "report_id": report_id,
            "alert_id": alert.get("alert_id", ""),
            "report_text": report_text,
            "severity": alert.get("severity", "HIGH"),
            "pattern_type": alert.get("pattern_type", ""),
            "entities": entities,
            "total_flow": alert.get("total_flow", 0),
            "confidence": alert.get("confidence", 0),
            "generated_at": datetime.now().isoformat(),
        }

    def generate_sar_from_case(self, case: Dict) -> Dict:
        """Generate SAR from a fraud case."""
        # Find matching alert
        matching_alerts = []
        case_entities = set(case.get("entities", []))
        for alert in self.alerts:
            alert_entities = set(alert.get("entities", []))
            if alert_entities & case_entities:
                matching_alerts.append(alert)

        if matching_alerts:
            return self.generate_sar(matching_alerts[0])

        # Create synthetic alert from case data
        pattern_map = {
            "circular_transaction": "Circular Transaction",
            "rapid_layering": "Rapid Layering",
            "smurfing": "Smurfing / Structuring",
            "shell_funnel": "Shell Company Funnel",
        }
        synthetic_alert = {
            "alert_id": f"CASE_{case.get('case_id', 'UNK')}",
            "pattern_type": pattern_map.get(case.get("pattern", ""), "Unknown"),
            "severity": "HIGH",
            "confidence": 85.0,
            "entities": case.get("entities", []),
            "entity_names": [self.graph.nodes[e].get("name", e) for e in case.get("entities", []) if self.graph.has_node(e)],
            "total_flow": case.get("total_amount", case.get("base_amount", 0)),
            "description": case.get("description", ""),
        }
        return self.generate_sar(synthetic_alert)

    def export_sar_pdf(self, sar: Dict, output_dir: str = "data/sar_reports") -> str:
        """Export SAR report as PDF."""
        os.makedirs(output_dir, exist_ok=True)
        filename = f"{sar['report_id']}.pdf"
        filepath = os.path.join(output_dir, filename)

        try:
            from reportlab.lib.pagesizes import A4
            from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
            from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
            from reportlab.lib.units import inch
            from reportlab.lib.colors import HexColor

            doc = SimpleDocTemplate(filepath, pagesize=A4,
                                     topMargin=0.75*inch, bottomMargin=0.75*inch,
                                     leftMargin=0.75*inch, rightMargin=0.75*inch)

            styles = getSampleStyleSheet()
            title_style = ParagraphStyle('SARTitle', parent=styles['Title'],
                                          fontSize=16, textColor=HexColor('#1a237e'))
            section_style = ParagraphStyle('SARSection', parent=styles['Heading2'],
                                            fontSize=12, textColor=HexColor('#37474f'),
                                            spaceBefore=16, spaceAfter=8)
            body_style = ParagraphStyle('SARBody', parent=styles['Normal'],
                                         fontSize=9, leading=12,
                                         fontName='Courier')
            alert_style = ParagraphStyle('SARAlert', parent=styles['Normal'],
                                          fontSize=9, leading=12,
                                          textColor=HexColor('#d32f2f'),
                                          fontName='Courier-Bold')

            story = []

            # Header
            story.append(Paragraph("SUSPICIOUS ACTIVITY REPORT", title_style))
            story.append(Paragraph(f"Report ID: {sar['report_id']} | Priority: {sar['severity']}", body_style))
            story.append(Paragraph(f"Generated: {sar['generated_at']}", body_style))
            story.append(Spacer(1, 20))

            # Content
            text = sar.get("report_text", "")
            sections = text.split("═" * 63)

            for section in sections:
                section = section.strip()
                if not section:
                    continue
                if "SECTION" in section:
                    lines = section.split("\n")
                    for line in lines:
                        line = line.strip()
                        if not line:
                            continue
                        if line.startswith("SECTION"):
                            story.append(Paragraph(line, section_style))
                        elif "CRITICAL" in line or "WARNING" in line:
                            story.append(Paragraph(line, alert_style))
                        else:
                            # Escape XML special chars
                            safe = line.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                            story.append(Paragraph(safe, body_style))
                else:
                    safe = section.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                    story.append(Paragraph(safe, body_style))
                story.append(Spacer(1, 8))

            doc.build(story)
            return filepath

        except ImportError:
            # Fallback: save as text file (explicit UTF-8 — cp1252 chokes on ₹ etc.)
            txt_path = filepath.replace(".pdf", ".txt")
            with open(txt_path, "w", encoding="utf-8") as f:
                f.write(sar.get("report_text", ""))
            return txt_path

    # ── Section Builders ──────────────────────────────────────

    def _build_suspect_info(self, entities: List[str]) -> str:
        lines = []
        for i, eid in enumerate(entities):
            if not self.graph.has_node(eid):
                continue
            ndata = dict(self.graph.nodes[eid])
            in_deg = self.graph.in_degree(eid)
            out_deg = self.graph.out_degree(eid)
            in_str = sum(self.graph[u][eid]["total_amount"] for u in self.graph.predecessors(eid))
            out_str = sum(self.graph[eid][v]["total_amount"] for v in self.graph.successors(eid))

            lines.append(f"Suspect {i+1}:")
            lines.append(f"  Entity ID: {eid}")
            lines.append(f"  Name: {ndata.get('name', 'N/A')}")
            lines.append(f"  Type: {ndata.get('type', 'N/A')}")
            lines.append(f"  Branch: {ndata.get('branch', 'N/A')}")
            lines.append(f"  Network Position: In-degree={in_deg}, Out-degree={out_deg}")
            lines.append(f"  Total Inflow: ₹{in_str:,.0f}")
            lines.append(f"  Total Outflow: ₹{out_str:,.0f}")
            lines.append("")

        return "\n".join(lines)

    def _build_activity_description(self, alert: Dict) -> str:
        desc = alert.get("description", "Suspicious pattern detected by RUDRA system.")
        pattern = alert.get("pattern_type", "")
        confidence = alert.get("confidence", 0)
        flow = alert.get("total_flow", 0)

        is_ml = alert.get("source") == "ml" or "ML" in pattern
        method = (
            "Stacked ML ensemble (XGBoost + GraphSAGE + GAT) edge classification"
            if is_ml else
            "Graph-based pattern analysis with multi-signal scoring"
        )

        tier = alert.get("tier")
        tier_label = {1: "Tier 1 — ML detection corroborated by a typology rule",
                      2: "Tier 2 — ML detection (model-only)",
                      3: "Tier 3 — typology rule"}.get(tier)
        corrob = alert.get("corroborated_by") or []

        extra = ""
        if tier_label:
            extra += f"\nConfidence Tier: {tier_label}"
        if corrob:
            extra += f"\nCorroborating Signals: {', '.join(corrob)}"
        if is_ml:
            extra += ("\nModel Explainability: per-feature SHAP attribution is available "
                      "for this edge (see the case explanation panel).")

        return (
            f"{desc}\n\n"
            f"Pattern Classification: {pattern}\n"
            f"Detection Confidence: {confidence}%\n"
            f"Total Flagged Flow: ₹{flow:,.0f}\n"
            f"Detection Method: {method}{extra}\n"
            f"Detection Timestamp: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
        )

    def _build_transaction_details(self, entities: List[str], alert: Dict) -> str:
        entity_txns = self.transactions[
            self.transactions["sender_id"].isin(entities) |
            self.transactions["receiver_id"].isin(entities)
        ]
        fraud_txns = entity_txns[entity_txns["is_fraud"]]

        lines = [
            f"Total Related Transactions: {len(entity_txns)}",
            f"Flagged as Fraudulent: {len(fraud_txns)}",
            f"Total Volume: ₹{entity_txns['amount'].sum():,.0f}",
            f"Fraud Volume: ₹{fraud_txns['amount'].sum():,.0f}",
            "",
            "Flagged Transaction Chain:",
        ]

        for _, txn in fraud_txns.sort_values("timestamp").head(30).iterrows():
            lines.append(
                f"  {txn['timestamp']} | {txn['sender_name']} → {txn['receiver_name']} "
                f"| ₹{txn['amount']:,.0f} | {txn['transaction_type']} | Case: {txn.get('fraud_case_id', 'N/A')}"
            )

        return "\n".join(lines)

    def _build_fund_flow_analysis(self, entities: List[str], alert: Dict) -> str:
        lines = [
            "Fund Flow Network Analysis:",
            f"  Entities in Pattern: {len(entities)}",
            f"  Total Flow Volume: ₹{alert.get('total_flow', 0):,.0f}",
            "",
            "Entity Flow Summary:",
        ]

        for eid in entities:
            if not self.graph.has_node(eid):
                continue
            ndata = self.graph.nodes[eid]
            in_str = sum(self.graph[u][eid]["total_amount"] for u in self.graph.predecessors(eid))
            out_str = sum(self.graph[eid][v]["total_amount"] for v in self.graph.successors(eid))
            net = in_str - out_str
            lines.append(
                f"  {ndata.get('name', eid)}: In ₹{in_str:,.0f} | Out ₹{out_str:,.0f} | "
                f"Net {'+'if net>=0 else ''}₹{net:,.0f}"
            )

        # Flow path
        names = alert.get("entity_names", [])
        if names:
            lines.append(f"\nDetected Flow Path:\n  {' → '.join(names)}")
            if "Circular" in alert.get("pattern_type", ""):
                lines.append(f"  → {names[0]} [CYCLE COMPLETE]")

        return "\n".join(lines)

    def _build_pattern_analysis(self, alert: Dict) -> str:
        pattern = alert.get("pattern_type", "")
        lines = [
            f"Pattern: {pattern}",
            f"Severity Assessment: {alert.get('severity', 'HIGH')}",
            f"Confidence Score: {alert.get('confidence', 0)}%",
            "",
            "Detection Reasoning:",
        ]

        if "Circular" in pattern:
            lines.extend([
                "  1. Closed-loop transaction path identified via cycle detection",
                "  2. Transaction amounts within the loop show low variance (≤15% deviation)",
                "  3. Funds return to originating entity — characteristic of round-tripping",
                "  4. Pattern inconsistent with legitimate business payment flows",
            ])
        elif "Layering" in pattern:
            lines.extend([
                "  1. Sequential chain of rapid fund transfers identified",
                "  2. Progressive amount decrease at each step (skimming/fee extraction)",
                f"  3. Chain involves {len(alert.get('entities', []))} entities including shell companies",
                "  4. Temporal pattern shows transfers within minutes — indicative of layering",
            ])
        elif "Smurfing" in pattern:
            lines.extend([
                "  1. Multiple transactions clustered below ₹2,00,000 reporting threshold",
                "  2. Low amount variability across transactions (structured pattern)",
                "  3. Common origin with multiple intermediary accounts (mule pattern)",
                "  4. Amount distribution shows deliberate avoidance of reporting requirements",
            ])
        elif "Funnel" in pattern:
            lines.extend([
                "  1. Multiple diverse sources converging into single entity",
                f"  2. Flow imbalance ratio: {alert.get('imbalance_ratio', 0):.1%}",
                f"  3. Sources span {alert.get('branch_diversity', 0)} different branches",
                "  4. Target entity exhibits shell company characteristics",
            ])

        lines.append(f"\nRisk Assessment: This pattern is consistent with {pattern.lower()} as defined under PMLA 2002.")

        return "\n".join(lines)

    def _build_regulatory_citations(self, alert: Dict) -> str:
        citations = [
            "1. Prevention of Money Laundering Act (PMLA), 2002 — Section 3 (Offense of money laundering)",
            "2. PMLA 2002 — Section 12 (Obligation of reporting entities)",
            "3. RBI Master Direction on KYC Direction, 2016 (updated 2023)",
            "   — Chapter VII: Suspicious Transaction Reporting",
            "4. RBI Framework for Real-time Fraud Risk Monitoring (FRM), 2023",
            "5. Digital Personal Data Protection Act (DPDP), 2023",
            "   — Section 8: Obligations of data fiduciaries",
            "6. Account Aggregator Framework (RBI/Sahamati), 2016 (amended 2021)",
            "   — Consent-based financial data sharing",
        ]
        if "Circular" in alert.get("pattern_type", ""):
            citations.append("\nSpecific: Round-tripping falls under PMLA Section 3 as an act of laundering proceeds of crime through circular fund flows.")
        elif "Layering" in alert.get("pattern_type", ""):
            citations.append("\nSpecific: Layering is the second stage of money laundering (placement → layering → integration), explicitly covered under PMLA Section 3.")
        elif "Smurfing" in alert.get("pattern_type", ""):
            citations.append("\nSpecific: Structuring/smurfing to avoid reporting thresholds violates RBI KYC Direction Chapter VII read with PMLA Rule 3.")
        elif "Funnel" in alert.get("pattern_type", ""):
            citations.append("\nSpecific: Use of shell companies for fund aggregation violates Companies Act 2013 (Section 248) and constitutes proceeds of crime under PMLA.")

        return "\n".join(citations)

    def _build_recommendations(self, alert: Dict) -> str:
        return (
            "1. Immediately flag all involved accounts for enhanced monitoring\n"
            "2. Initiate Enhanced Due Diligence (EDD) for all entity accounts in the pattern\n"
            "3. Verify KYC documents and beneficial ownership of all entities\n"
            "4. File STR (Suspicious Transaction Report) with FIU-IND within 7 days\n"
            "5. Preserve all transaction records and communication logs\n"
            "6. Consider temporary account freeze pending investigation\n"
            "7. Cross-reference with existing FIU-IND databases for related patterns\n"
            "8. Coordinate with compliance team for regulatory filing timeline\n"
            f"9. Monitor for related fund flows involving the same entities\n"
            "10. Document investigation trail for regulatory audit compliance"
        )

    def _build_supporting_docs(self, report_id: str, alert: Dict) -> str:
        """Document set bundled with this SAR — pulled from the single source
        of truth in `fiu_package.FIU_PACKAGE_FILES` so the two files can't drift.
        """
        from fiu_package import package_files_listing

        alert_id = alert.get("alert_id", "UNKNOWN")
        entities = alert.get("entities", [])
        return (
            f"The complete evidence package can be downloaded via:\n"
            f"    GET /api/fiu/package/{alert_id}\n"
            f"\nPackage contents (zip):\n"
            f"{package_files_listing(alert_id)}\n"
            f"\nTotal Supporting Entities: {len(entities)}\n"
            f"Pattern Type: {alert.get('pattern_type', 'N/A')}\n"
            f"Confidence Level: {alert.get('confidence', 0)}%\n"
            f"Detection Engine: RUDRA Graph-based Pattern Detection + XGBoost+GraphSAGE+GAT Ensemble"
        )
